version: "3.8"
services:
  backend-service-mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
